### ISSUE TITLE
Crush world when start

### ISSUE THREAD

**Issue by WildPandaUa** [Fexcraft/FCL#8] opened 2024-07-13 07:34 UTC
Time: 7/13/24 10:31 AM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at net.fexcraft.mod.fsmm.events.PlayerEvents.onPlayerLogin(PlayerEvents.java:30)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_677_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Fexcraft** [comment] 2024-07-13 08:30
FCL and FSMM version?
The crash doesn't actually happen in FCL.

**Comment by WildPandaUa** [comment] 2024-07-14 10:55
FCL-1.12.82 FSMM-2.7.0

**Comment by WildPandaUa** [comment] 2024-07-14 11:13
Problen in FSMM?

**Comment by Fexcraft** [comment] 2024-07-14 18:45
> Problen in FSMM?
> 

Yesn't, it's an old version, it could be the issue is fixed in a newer version.

**Comment by Fexcraft** [comment] 2024-07-14 18:47
Actually there's 2.7.1, and 2.7.0 is marked as beta, very likely you shouldn't use it instead of 2.7.1

**Comment by WildPandaUa** [comment] 2024-07-15 13:16
Yes, the newer version helped, but then the oxygen currency provider doesn't work(

**Comment by Fexcraft** [comment] 2024-07-25 08:16
Not sure what to do in regards to that, newer FSMM doesn't have direct Oxygen Compat anymore due to larger code changes, and since I can't update the Oxygen Currency Provider, I can't really do anything about that directly.
I _could_ perhaps make a new Currency Provider and post it separately on CF.

_But this is not a FCL issue, so closing this issue. If you want to chat on this topic consider joining the Discord Server._

**Closed as not planned** 2024-07-25 08:16 UTC
